[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"



[build.environment]
  NODE_VERSION = 18.18.0 # Specifica la versione di Node.js che desideri utilizzare

[build.command]
  command = "npm install" # Installa le dipendenze
  command = "node app.js" # Esegui il comando di build (se necessario)



