[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"



[build.command]
  command = "npm install" # Installa le dipendenze
  command = "node app.js" # Esegui il comando di build (se necessario)



